# This workflow will build a Swift project
name: Swift

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-22.04
    env:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USERNAME: vapor
      DATABASE_PASSWORD: vapor_test
      DATABASE_NAME: vapor

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4.2.0
      with:
        path: whooshing.template-bare/.build
        
    - name: Cache
      uses: actions/cache@v4.2.0
      with:
        path: whooshing.template-bare/.build
        key: ${{ runner.os }}-build-${{ hashFiles('whooshing.template-bare/Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-build-
    
    - name: Setup PostgreSQL
      uses: Harmon758/postgresql-action@v1.0.0
      with:
        postgresql_version: 17.2
        postgresql_db: ${{ env.DATABASE_NAME }}
        postgresql_user: ${{ env.DATABASE_USERNAME }}
        postgresql_password: ${{ env.DATABASE_PASSWORD }}

    - name: Build
      run: |
        cd whooshing.template-bare
        swift build -v

    - name: Run tests
      run: |
        cd whooshing.template-bare
        swift test -v
